name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the main branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # You can specify a different version if needed

      # Run Flutter build for web
      - name: Build Flutter Web App
        run: flutter build web

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this secret
          publish_dir: ./build/web  # The directory where the built web app is located
